SELECT	S.SESSION_ID ,
		S.STATUS ,
		S.HOST_NAME ,
		DB_NAME(dbid) DBNAME ,
		C.CLIENT_NET_ADDRESS ,
		CASE WHEN S.LOGIN_NAME = S.ORIGINAL_LOGIN_NAME THEN S.LOGIN_NAME
			 ELSE S.LOGIN_NAME + ' (' + S.ORIGINAL_LOGIN_NAME + ')'
		END AS 'LOGIN_NAME' ,
		S.PROGRAM_NAME ,
		C.CONNECT_TIME , -- DIFFRENT BETWEEN CONNECT & LOGIN TIME IS TIME TAKEN BY PRELOGON ACTIVITIES
		S.LOGIN_TIME ,
		CASE S.TRANSACTION_ISOLATION_LEVEL
		  WHEN 0 THEN 'UNSPECIFIED'
		  WHEN 1 THEN 'READUNCOMITTED'
		  WHEN 2 THEN 'READCOMMITTED'
		  WHEN 3 THEN 'REPEATABLE'
		  WHEN 4 THEN 'SERIALIZABLE'
		  WHEN 5 THEN 'SNAPSHOT'
		  ELSE CAST(S.TRANSACTION_ISOLATION_LEVEL AS VARCHAR(32))
		END AS TRANSACTION_ISOLATION_LEVEL_NAME ,
		S.LAST_SUCCESSFUL_LOGON , -- REQUIRES 'COMMON CRITERIA COMPLIANCE ENABLED' OPTION VIA SP_CONFIGURE.
		S.LAST_UNSUCCESSFUL_LOGON , -- REQUIRES 'COMMON CRITERIA COMPLIANCE ENABLED' OPTION VIA SP_CONFIGURE.
		S.UNSUCCESSFUL_LOGONS , -- REQUIRES 'COMMON CRITERIA COMPLIANCE ENABLED' OPTION VIA SP_CONFIGURE.
		S.CPU_TIME AS CPU_TIME_MS ,
		S.MEMORY_USAGE AS MEMORY_USAGE_PAGES ,
		S.ROW_COUNT ,
		S.PREV_ERROR ,
		S.LAST_REQUEST_START_TIME ,
		S.LAST_REQUEST_END_TIME ,
		C.NET_TRANSPORT ,
		C.PROTOCOL_TYPE ,
		S.LANGUAGE ,
		S.DATE_FORMAT ,
		ST.TEXT AS QUERY_TEXT
FROM	SYS.DM_EXEC_SESSIONS S
		FULL OUTER JOIN SYS.DM_EXEC_CONNECTIONS C ON C.SESSION_ID = S.SESSION_ID
		CROSS APPLY SYS.DM_EXEC_SQL_TEXT(C.MOST_RECENT_SQL_HANDLE) ST
WHERE	S.SESSION_ID IS NULL
		OR S.SESSION_ID > 50
ORDER BY S.SESSION_ID